name: cas-edge-proxy-alias-ips

services:
  proxy:
    image: cas-edge-proxy:1.0.0
    build:
      context: .
      args:
        VERSION: "1.0.0"
    container_name: cas-edge-proxy
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp:size=16m,mode=1777
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config/config.json:/config/config.json:ro
    ports:
      - "127.0.0.1:9090:9090/tcp"
      - "192.168.2.2:1600:11601/tcp"
      - "10.3.11.71:1600:11601/tcp"
      - "10.3.11.135:80:18001/tcp"
      - "10.3.11.135:443:18443/tcp"
      - "10.3.11.135:554:18554/tcp"
      - "10.3.11.136:80:28001/tcp"
      - "10.3.11.136:443:28443/tcp"
      - "10.3.11.136:554:28554/tcp"
    stop_grace_period: 15s
